### ISSUE TITLE
Text-value for line is wrong when semicolon is used

### ISSUE THREAD

**Issue by fflaten** [nohwnd/Profiler#26]
```
[17:05:06] C:\Git\Profiler> $trace = Trace-Script { 1; 2 }
[17:06:20] C:\Git\Profiler> $trace.AllLines | ft

Percent HitCount Duration         Average          SelfDuration     SelfAverage      Name                                 Line Text Path
------- -------- --------         -------          ------------     -----------      ----                                 ---- ---- ----
    100        4 00:00:00.0000225 00:00:00.0000056 00:00:00.0000225 00:00:00.0000056 e6898893-8ded-4ee3-a620-a4c7761c1b25    1 {    e6898893-8ded-4ee3-a620-a4c7761c1b25


[17:06:22] C:\Git\Profiler> $trace.AllLines.CommandHits.Values | ft

Line Column HitCount SelfDuration     Text
---- ------ -------- ------------     ----
   1     31        1 00:00:00.0000048 {
   1     33        1 00:00:00.0000034 1
   1     36        1 00:00:00.0000034 2
   1     38        1 00:00:00.0000109 }
```

**Comment by fflaten** [comment]
Bonus-question: should the hitcount on the line be 4 in this case ? The line was hit once even though there were 4 command hits.

**Comment by nohwnd** [comment]
I think I added if text.length -gt currenttextlenght, then replace it, in your code 1 is the same size as {, so it stays, I should check for '{' explicity as well I think.

This is because I don't know when I encounter which part of the code, I think I will first see the biggest part of the code on the second hit, where { is enter the sb, and then we get more of the sb content. 

This worked better when we loaded the whole source from files, because there we get the whole line always.

```
$t=Trace-Script { 1; 2 } ; $t.Top50Duration | ft ; $t.Top50Duration[0].CommandHits.values | ft
```

These are the unique values we see per line (but I think I broke it in 3.0.0). I think I need to reconstruct the line better using the column as well.

**Comment by nohwnd** [comment]
Hitcount: yes. I tried to get rid of it, but if you do foreach then half of the time accounts for the } events, I was not sure how to get rid of that. I think we have HitCount  which is tracking all the commands on the line added, if we had HitPerUniqueCommand, then each should definitely have 1 in them. This should be in the CommandHits view

**Comment by nohwnd** [comment]
I forgot I keep all scriptblocks.
